name: Validate files defining AWS service features

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'To manually launch this workflow, provide the PR number'
        type: number
        required: false
      localstack_meta_ref:
        description: 'To manually launch this workflow, provide branch to checkout in the localstack/meta'
        type: string
        required: false
  pull_request_target:
    paths:
      - localstack-core/localstack/services/**
    types: [labeled, unlabeled, opened, edited, synchronize]
    # only enforce for PRs targeting the master branch
    branches:
    - master

jobs:
  validate-features-files:
      uses: .github/workflows/pr-validate-features-files.yml@main
      with:
        pr_number: ${{ inputs.pr_number }}
        localstack_meta_ref: ${{ inputs.localstack_meta_ref }}
